name: redo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  analyzer: ^4.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: lib/assets/fonts/GalanoGrotesqueThin.otf
          weight: 100
        - asset: lib/assets/fonts/GalanoGrotesqueExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/GalanoGrotesqueLight.otf
          weight: 300
        - asset: lib/assets/fonts/GalanoGrotesqueRegular.otf
          weight: 400
        - asset: lib/assets/fonts/GalanoGrotesqueMedium.otf
          weight: 500
        - asset: lib/assets/fonts/GalanoGrotesqueSemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/GalanoGrotesqueBold.otf
          weight: 700
        - asset: lib/assets/fonts/GalanoGrotesqueExtraBold.otf
          weight: 800
        - asset: lib/assets/fonts/GalanoGrotesqueBlack.otf
          weight: 900