import 'package:redo/utils/enums/prirority.dart';

class TestTodos {
  List<Map<String, dynamic>> todos = [
    {
      "title": "Buy groceries",
      "description": "Buy milk, eggs, and bread",
      "location": "Supermarket",
      "isDone": false,
      "tags": ["shopping", "urgent"],
      "colorHex": "#000000",
      "priority": Prirority.high,
      "scheduledAt": DateTime(2024, 8, 1, 10, 0),
      "reminderAt": DateTime(2024, 8, 1, 9, 0),
    },
    {
      "title": "Morning run",
      "description": "Run 5 km in the park",
      "location": "Central Park",
      "isDone": true,
      "tags": ["exercise", "morning"],
      "colorHex": "#000000",
      "priority": Prirority.medium,
      "scheduledAt": DateTime(2024, 8, 1, 6, 0),
      "reminderAt": DateTime(2024, 8, 1, 5, 45),
    },
    {
      "title": "Team meeting",
      "description": "Discuss project updates",
      "location": "Office",
      "isDone": false,
      "tags": ["work", "meeting"],
      "colorHex": "#000000",
      "priority": Prirority.high,
      "scheduledAt": DateTime(2024, 8, 1, 14, 0),
      "reminderAt": DateTime(2024, 8, 1, 13, 45),
    },
    {
      "title": "Doctor's appointment",
      "description": "Annual check-up",
      "location": "Clinic",
      "isDone": false,
      "tags": ["health"],
      "colorHex": "#000000",
      "priority": Prirority.high,
      "scheduledAt": DateTime(2024, 8, 1, 16, 0),
      "reminderAt": DateTime(2024, 8, 1, 15, 45),
    },
    {
      "title": "Read a book",
      "description": "Finish reading '1984' by George Orwell",
      "isDone": true,
      "tags": ["leisure", "reading"],
      "colorHex": "#000000",
      "priority": Prirority.low,
      "scheduledAt": DateTime(2024, 8, 1, 20, 0),
      "reminderAt": DateTime(2024, 8, 1, 19, 45),
    },
    {
      "title": "Birthday party",
      "description": "Attend Jane's birthday party",
      "location": "Jane's house",
      "isDone": false,
      "tags": ["social", "birthday"],
      "colorHex": "#000000",
      "priority": Prirority.medium,
      "scheduledAt": DateTime(2024, 8, 1, 18, 0),
      "reminderAt": DateTime(2024, 8, 1, 17, 45),
    },
    {
      "title": "Complete assignment",
      "description": "Finish the math assignment",
      "isDone": false,
      "tags": ["school", "assignment"],
      "colorHex": "#000000",
      "priority": Prirority.high,
      "scheduledAt": DateTime(2024, 8, 2, 12, 0),
      "reminderAt": DateTime(2024, 8, 2, 11, 45),
    },
    {
      "title": "Yoga session",
      "description": "Attend morning yoga session",
      "location": "Yoga studio",
      "isDone": true,
      "tags": ["exercise", "wellness"],
      "colorHex": "#000000",
      "priority": Prirority.low,
      "scheduledAt": DateTime(2024, 8, 2, 7, 0),
      "reminderAt": DateTime(2024, 8, 2, 6, 45),
    },
    {
      "title": "Call parents",
      "description": "Catch up with parents over the phone",
      "isDone": false,
      "tags": ["family", "call"],
      "colorHex": "#000000",
      "priority": Prirority.medium,
      "scheduledAt": DateTime(2024, 8, 2, 19, 0),
      "reminderAt": DateTime(2024, 8, 2, 18, 45),
    },
    {
      "title": "Clean the house",
      "description": "Vacuum and dust all rooms",
      "isDone": false,
      "tags": ["chores", "cleaning"],
      "colorHex": "#000000",
      "priority": Prirority.medium,
      "scheduledAt": DateTime(2024, 8, 3, 10, 0),
      "reminderAt": DateTime(2024, 8, 3, 9, 45),
    },
  ];
}
